/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ninjaone.kafka.associate.service.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum AssociateServiceStatus implements org.apache.avro.generic.GenericEnumSymbol<AssociateServiceStatus> {
  PENDING, VALIDATED, INVALID  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"AssociateServiceStatus\",\"namespace\":\"com.ninjaone.kafka.associate.service.avro.model\",\"symbols\":[\"PENDING\",\"VALIDATED\",\"INVALID\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
