/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ninjaone.kafka.associate.service.avro.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class DeviceService extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3823908083639975417L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DeviceService\",\"namespace\":\"com.ninjaone.kafka.associate.service.avro.model\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"serviceTypeId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"typeDeviceId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<DeviceService> ENCODER =
      new BinaryMessageEncoder<DeviceService>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DeviceService> DECODER =
      new BinaryMessageDecoder<DeviceService>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<DeviceService> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<DeviceService> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<DeviceService> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<DeviceService>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this DeviceService to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a DeviceService from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a DeviceService instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static DeviceService fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String id;
  private java.lang.String serviceTypeId;
  private java.lang.String typeDeviceId;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DeviceService() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param serviceTypeId The new value for serviceTypeId
   * @param typeDeviceId The new value for typeDeviceId
   */
  public DeviceService(java.lang.String id, java.lang.String serviceTypeId, java.lang.String typeDeviceId) {
    this.id = id;
    this.serviceTypeId = serviceTypeId;
    this.typeDeviceId = typeDeviceId;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return serviceTypeId;
    case 2: return typeDeviceId;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = value$ != null ? value$.toString() : null; break;
    case 1: serviceTypeId = value$ != null ? value$.toString() : null; break;
    case 2: typeDeviceId = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.String getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.String value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'serviceTypeId' field.
   * @return The value of the 'serviceTypeId' field.
   */
  public java.lang.String getServiceTypeId() {
    return serviceTypeId;
  }


  /**
   * Sets the value of the 'serviceTypeId' field.
   * @param value the value to set.
   */
  public void setServiceTypeId(java.lang.String value) {
    this.serviceTypeId = value;
  }

  /**
   * Gets the value of the 'typeDeviceId' field.
   * @return The value of the 'typeDeviceId' field.
   */
  public java.lang.String getTypeDeviceId() {
    return typeDeviceId;
  }


  /**
   * Sets the value of the 'typeDeviceId' field.
   * @param value the value to set.
   */
  public void setTypeDeviceId(java.lang.String value) {
    this.typeDeviceId = value;
  }

  /**
   * Creates a new DeviceService RecordBuilder.
   * @return A new DeviceService RecordBuilder
   */
  public static com.ninjaone.kafka.associate.service.avro.model.DeviceService.Builder newBuilder() {
    return new com.ninjaone.kafka.associate.service.avro.model.DeviceService.Builder();
  }

  /**
   * Creates a new DeviceService RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DeviceService RecordBuilder
   */
  public static com.ninjaone.kafka.associate.service.avro.model.DeviceService.Builder newBuilder(com.ninjaone.kafka.associate.service.avro.model.DeviceService.Builder other) {
    if (other == null) {
      return new com.ninjaone.kafka.associate.service.avro.model.DeviceService.Builder();
    } else {
      return new com.ninjaone.kafka.associate.service.avro.model.DeviceService.Builder(other);
    }
  }

  /**
   * Creates a new DeviceService RecordBuilder by copying an existing DeviceService instance.
   * @param other The existing instance to copy.
   * @return A new DeviceService RecordBuilder
   */
  public static com.ninjaone.kafka.associate.service.avro.model.DeviceService.Builder newBuilder(com.ninjaone.kafka.associate.service.avro.model.DeviceService other) {
    if (other == null) {
      return new com.ninjaone.kafka.associate.service.avro.model.DeviceService.Builder();
    } else {
      return new com.ninjaone.kafka.associate.service.avro.model.DeviceService.Builder(other);
    }
  }

  /**
   * RecordBuilder for DeviceService instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DeviceService>
    implements org.apache.avro.data.RecordBuilder<DeviceService> {

    private java.lang.String id;
    private java.lang.String serviceTypeId;
    private java.lang.String typeDeviceId;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.ninjaone.kafka.associate.service.avro.model.DeviceService.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.serviceTypeId)) {
        this.serviceTypeId = data().deepCopy(fields()[1].schema(), other.serviceTypeId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.typeDeviceId)) {
        this.typeDeviceId = data().deepCopy(fields()[2].schema(), other.typeDeviceId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing DeviceService instance
     * @param other The existing instance to copy.
     */
    private Builder(com.ninjaone.kafka.associate.service.avro.model.DeviceService other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.serviceTypeId)) {
        this.serviceTypeId = data().deepCopy(fields()[1].schema(), other.serviceTypeId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.typeDeviceId)) {
        this.typeDeviceId = data().deepCopy(fields()[2].schema(), other.typeDeviceId);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.String getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.ninjaone.kafka.associate.service.avro.model.DeviceService.Builder setId(java.lang.String value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.ninjaone.kafka.associate.service.avro.model.DeviceService.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'serviceTypeId' field.
      * @return The value.
      */
    public java.lang.String getServiceTypeId() {
      return serviceTypeId;
    }


    /**
      * Sets the value of the 'serviceTypeId' field.
      * @param value The value of 'serviceTypeId'.
      * @return This builder.
      */
    public com.ninjaone.kafka.associate.service.avro.model.DeviceService.Builder setServiceTypeId(java.lang.String value) {
      validate(fields()[1], value);
      this.serviceTypeId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'serviceTypeId' field has been set.
      * @return True if the 'serviceTypeId' field has been set, false otherwise.
      */
    public boolean hasServiceTypeId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'serviceTypeId' field.
      * @return This builder.
      */
    public com.ninjaone.kafka.associate.service.avro.model.DeviceService.Builder clearServiceTypeId() {
      serviceTypeId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'typeDeviceId' field.
      * @return The value.
      */
    public java.lang.String getTypeDeviceId() {
      return typeDeviceId;
    }


    /**
      * Sets the value of the 'typeDeviceId' field.
      * @param value The value of 'typeDeviceId'.
      * @return This builder.
      */
    public com.ninjaone.kafka.associate.service.avro.model.DeviceService.Builder setTypeDeviceId(java.lang.String value) {
      validate(fields()[2], value);
      this.typeDeviceId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'typeDeviceId' field has been set.
      * @return True if the 'typeDeviceId' field has been set, false otherwise.
      */
    public boolean hasTypeDeviceId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'typeDeviceId' field.
      * @return This builder.
      */
    public com.ninjaone.kafka.associate.service.avro.model.DeviceService.Builder clearTypeDeviceId() {
      typeDeviceId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DeviceService build() {
      try {
        DeviceService record = new DeviceService();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.String) defaultValue(fields()[0]);
        record.serviceTypeId = fieldSetFlags()[1] ? this.serviceTypeId : (java.lang.String) defaultValue(fields()[1]);
        record.typeDeviceId = fieldSetFlags()[2] ? this.typeDeviceId : (java.lang.String) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DeviceService>
    WRITER$ = (org.apache.avro.io.DatumWriter<DeviceService>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DeviceService>
    READER$ = (org.apache.avro.io.DatumReader<DeviceService>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










