/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ninjaone.kafka.associate.service.avro.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class DeviceServiceResponseAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6118343390875230193L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DeviceServiceResponseAvroModel\",\"namespace\":\"com.ninjaone.kafka.associate.service.avro.model\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\",\"default\":\"00000000-0000-0000-0000-000000000000\"}},{\"name\":\"serviceTypeId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\",\"default\":\"00000000-0000-0000-0000-000000000000\"}},{\"name\":\"price\",\"type\":{\"type\":\"bytes\",\"logicalType\":\"decimal\",\"precision\":10,\"scale\":2}},{\"name\":\"message\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"validation\",\"type\":{\"type\":\"enum\",\"name\":\"DeviceServiceStatus\",\"symbols\":[\"PENDING\",\"VALIDATED\",\"INVALID\"]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.DecimalConversion());
  }

  private static final BinaryMessageEncoder<DeviceServiceResponseAvroModel> ENCODER =
      new BinaryMessageEncoder<DeviceServiceResponseAvroModel>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DeviceServiceResponseAvroModel> DECODER =
      new BinaryMessageDecoder<DeviceServiceResponseAvroModel>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<DeviceServiceResponseAvroModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<DeviceServiceResponseAvroModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<DeviceServiceResponseAvroModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<DeviceServiceResponseAvroModel>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this DeviceServiceResponseAvroModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a DeviceServiceResponseAvroModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a DeviceServiceResponseAvroModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static DeviceServiceResponseAvroModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String id;
  private java.lang.String serviceTypeId;
  private java.math.BigDecimal price;
  private java.lang.String message;
  private com.ninjaone.kafka.associate.service.avro.model.DeviceServiceStatus validation;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DeviceServiceResponseAvroModel() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param serviceTypeId The new value for serviceTypeId
   * @param price The new value for price
   * @param message The new value for message
   * @param validation The new value for validation
   */
  public DeviceServiceResponseAvroModel(java.lang.String id, java.lang.String serviceTypeId, java.math.BigDecimal price, java.lang.String message, com.ninjaone.kafka.associate.service.avro.model.DeviceServiceStatus validation) {
    this.id = id;
    this.serviceTypeId = serviceTypeId;
    this.price = price;
    this.message = message;
    this.validation = validation;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return serviceTypeId;
    case 2: return price;
    case 3: return message;
    case 4: return validation;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      new org.apache.avro.Conversions.DecimalConversion(),
      null,
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = value$ != null ? value$.toString() : null; break;
    case 1: serviceTypeId = value$ != null ? value$.toString() : null; break;
    case 2: price = (java.math.BigDecimal)value$; break;
    case 3: message = value$ != null ? value$.toString() : null; break;
    case 4: validation = (com.ninjaone.kafka.associate.service.avro.model.DeviceServiceStatus)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.String getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.String value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'serviceTypeId' field.
   * @return The value of the 'serviceTypeId' field.
   */
  public java.lang.String getServiceTypeId() {
    return serviceTypeId;
  }


  /**
   * Sets the value of the 'serviceTypeId' field.
   * @param value the value to set.
   */
  public void setServiceTypeId(java.lang.String value) {
    this.serviceTypeId = value;
  }

  /**
   * Gets the value of the 'price' field.
   * @return The value of the 'price' field.
   */
  public java.math.BigDecimal getPrice() {
    return price;
  }


  /**
   * Sets the value of the 'price' field.
   * @param value the value to set.
   */
  public void setPrice(java.math.BigDecimal value) {
    this.price = value;
  }

  /**
   * Gets the value of the 'message' field.
   * @return The value of the 'message' field.
   */
  public java.lang.String getMessage() {
    return message;
  }


  /**
   * Sets the value of the 'message' field.
   * @param value the value to set.
   */
  public void setMessage(java.lang.String value) {
    this.message = value;
  }

  /**
   * Gets the value of the 'validation' field.
   * @return The value of the 'validation' field.
   */
  public com.ninjaone.kafka.associate.service.avro.model.DeviceServiceStatus getValidation() {
    return validation;
  }


  /**
   * Sets the value of the 'validation' field.
   * @param value the value to set.
   */
  public void setValidation(com.ninjaone.kafka.associate.service.avro.model.DeviceServiceStatus value) {
    this.validation = value;
  }

  /**
   * Creates a new DeviceServiceResponseAvroModel RecordBuilder.
   * @return A new DeviceServiceResponseAvroModel RecordBuilder
   */
  public static com.ninjaone.kafka.associate.service.avro.model.DeviceServiceResponseAvroModel.Builder newBuilder() {
    return new com.ninjaone.kafka.associate.service.avro.model.DeviceServiceResponseAvroModel.Builder();
  }

  /**
   * Creates a new DeviceServiceResponseAvroModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DeviceServiceResponseAvroModel RecordBuilder
   */
  public static com.ninjaone.kafka.associate.service.avro.model.DeviceServiceResponseAvroModel.Builder newBuilder(com.ninjaone.kafka.associate.service.avro.model.DeviceServiceResponseAvroModel.Builder other) {
    if (other == null) {
      return new com.ninjaone.kafka.associate.service.avro.model.DeviceServiceResponseAvroModel.Builder();
    } else {
      return new com.ninjaone.kafka.associate.service.avro.model.DeviceServiceResponseAvroModel.Builder(other);
    }
  }

  /**
   * Creates a new DeviceServiceResponseAvroModel RecordBuilder by copying an existing DeviceServiceResponseAvroModel instance.
   * @param other The existing instance to copy.
   * @return A new DeviceServiceResponseAvroModel RecordBuilder
   */
  public static com.ninjaone.kafka.associate.service.avro.model.DeviceServiceResponseAvroModel.Builder newBuilder(com.ninjaone.kafka.associate.service.avro.model.DeviceServiceResponseAvroModel other) {
    if (other == null) {
      return new com.ninjaone.kafka.associate.service.avro.model.DeviceServiceResponseAvroModel.Builder();
    } else {
      return new com.ninjaone.kafka.associate.service.avro.model.DeviceServiceResponseAvroModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for DeviceServiceResponseAvroModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DeviceServiceResponseAvroModel>
    implements org.apache.avro.data.RecordBuilder<DeviceServiceResponseAvroModel> {

    private java.lang.String id;
    private java.lang.String serviceTypeId;
    private java.math.BigDecimal price;
    private java.lang.String message;
    private com.ninjaone.kafka.associate.service.avro.model.DeviceServiceStatus validation;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.ninjaone.kafka.associate.service.avro.model.DeviceServiceResponseAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.serviceTypeId)) {
        this.serviceTypeId = data().deepCopy(fields()[1].schema(), other.serviceTypeId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.price)) {
        this.price = data().deepCopy(fields()[2].schema(), other.price);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.message)) {
        this.message = data().deepCopy(fields()[3].schema(), other.message);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.validation)) {
        this.validation = data().deepCopy(fields()[4].schema(), other.validation);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing DeviceServiceResponseAvroModel instance
     * @param other The existing instance to copy.
     */
    private Builder(com.ninjaone.kafka.associate.service.avro.model.DeviceServiceResponseAvroModel other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.serviceTypeId)) {
        this.serviceTypeId = data().deepCopy(fields()[1].schema(), other.serviceTypeId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.price)) {
        this.price = data().deepCopy(fields()[2].schema(), other.price);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.message)) {
        this.message = data().deepCopy(fields()[3].schema(), other.message);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.validation)) {
        this.validation = data().deepCopy(fields()[4].schema(), other.validation);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.String getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.ninjaone.kafka.associate.service.avro.model.DeviceServiceResponseAvroModel.Builder setId(java.lang.String value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.ninjaone.kafka.associate.service.avro.model.DeviceServiceResponseAvroModel.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'serviceTypeId' field.
      * @return The value.
      */
    public java.lang.String getServiceTypeId() {
      return serviceTypeId;
    }


    /**
      * Sets the value of the 'serviceTypeId' field.
      * @param value The value of 'serviceTypeId'.
      * @return This builder.
      */
    public com.ninjaone.kafka.associate.service.avro.model.DeviceServiceResponseAvroModel.Builder setServiceTypeId(java.lang.String value) {
      validate(fields()[1], value);
      this.serviceTypeId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'serviceTypeId' field has been set.
      * @return True if the 'serviceTypeId' field has been set, false otherwise.
      */
    public boolean hasServiceTypeId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'serviceTypeId' field.
      * @return This builder.
      */
    public com.ninjaone.kafka.associate.service.avro.model.DeviceServiceResponseAvroModel.Builder clearServiceTypeId() {
      serviceTypeId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'price' field.
      * @return The value.
      */
    public java.math.BigDecimal getPrice() {
      return price;
    }


    /**
      * Sets the value of the 'price' field.
      * @param value The value of 'price'.
      * @return This builder.
      */
    public com.ninjaone.kafka.associate.service.avro.model.DeviceServiceResponseAvroModel.Builder setPrice(java.math.BigDecimal value) {
      validate(fields()[2], value);
      this.price = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'price' field has been set.
      * @return True if the 'price' field has been set, false otherwise.
      */
    public boolean hasPrice() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'price' field.
      * @return This builder.
      */
    public com.ninjaone.kafka.associate.service.avro.model.DeviceServiceResponseAvroModel.Builder clearPrice() {
      price = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'message' field.
      * @return The value.
      */
    public java.lang.String getMessage() {
      return message;
    }


    /**
      * Sets the value of the 'message' field.
      * @param value The value of 'message'.
      * @return This builder.
      */
    public com.ninjaone.kafka.associate.service.avro.model.DeviceServiceResponseAvroModel.Builder setMessage(java.lang.String value) {
      validate(fields()[3], value);
      this.message = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'message' field has been set.
      * @return True if the 'message' field has been set, false otherwise.
      */
    public boolean hasMessage() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'message' field.
      * @return This builder.
      */
    public com.ninjaone.kafka.associate.service.avro.model.DeviceServiceResponseAvroModel.Builder clearMessage() {
      message = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'validation' field.
      * @return The value.
      */
    public com.ninjaone.kafka.associate.service.avro.model.DeviceServiceStatus getValidation() {
      return validation;
    }


    /**
      * Sets the value of the 'validation' field.
      * @param value The value of 'validation'.
      * @return This builder.
      */
    public com.ninjaone.kafka.associate.service.avro.model.DeviceServiceResponseAvroModel.Builder setValidation(com.ninjaone.kafka.associate.service.avro.model.DeviceServiceStatus value) {
      validate(fields()[4], value);
      this.validation = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'validation' field has been set.
      * @return True if the 'validation' field has been set, false otherwise.
      */
    public boolean hasValidation() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'validation' field.
      * @return This builder.
      */
    public com.ninjaone.kafka.associate.service.avro.model.DeviceServiceResponseAvroModel.Builder clearValidation() {
      validation = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DeviceServiceResponseAvroModel build() {
      try {
        DeviceServiceResponseAvroModel record = new DeviceServiceResponseAvroModel();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.String) defaultValue(fields()[0]);
        record.serviceTypeId = fieldSetFlags()[1] ? this.serviceTypeId : (java.lang.String) defaultValue(fields()[1]);
        record.price = fieldSetFlags()[2] ? this.price : (java.math.BigDecimal) defaultValue(fields()[2]);
        record.message = fieldSetFlags()[3] ? this.message : (java.lang.String) defaultValue(fields()[3]);
        record.validation = fieldSetFlags()[4] ? this.validation : (com.ninjaone.kafka.associate.service.avro.model.DeviceServiceStatus) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DeviceServiceResponseAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<DeviceServiceResponseAvroModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DeviceServiceResponseAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<DeviceServiceResponseAvroModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










